### ISSUE TITLE
`phpparser` is not present in this project

### ISSUE THREAD

**Issue by voidtek** [openeuropa/oe_media#15]
1. Add in composer.json on the require-dev
```
"nikic/php-parser": "~3.0",
```

2. Add on grumphp.yml
```
  extra_tasks:
    phpparser:
      ignore_patterns: "%tasks.phpcs.ignore_patterns%"
      visitors:
        declare_strict_types: ~
      triggered_by: "%tasks.phpcs.triggered_by%"

  extensions:
  - OpenEuropa\CodeReview\ExtraTasksExtension
```

3. Fix issues on files.
